apiVersion: v1
kind: Service
metadata:
  annotations:
    appGroup: nginx-ingress
  name: default-http-backend
  namespace: nginx-ingress
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: default-http-backend
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    appGroup: nginx-ingress
  name: nginx-ingress
  namespace: nginx-ingress
spec:
  ports:
  - name: http
    nodePort: 30080
    port: 80
    targetPort: http
  - name: https
    nodePort: 30443
    port: 443
    targetPort: https
  selector:
    k8s-app: nginx-ingress-lb
  type: NodePort
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    appGroup: nginx-ingress
  name: default-http-backend
  namespace: nginx-ingress
spec:
  replicas: 1
  template:
    metadata:
      annotations:
        appGroup: nginx-ingress
      labels:
        app: default-http-backend
    spec:
      containers:
      - image: gcr.io/google_containers/defaultbackend:1.0
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 30
          timeoutSeconds: 5
        name: default-http-backend
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: 10m
            memory: 20Mi
          requests:
            cpu: 10m
            memory: 20Mi
      terminationGracePeriodSeconds: 60
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    appGroup: nginx-ingress
  name: nginx-ingress-controller
  namespace: nginx-ingress
spec:
  replicas: 1
  revisionHistoryLimit: 3
  template:
    metadata:
      annotations:
        appGroup: nginx-ingress
      labels:
        k8s-app: nginx-ingress-lb
    spec:
      containers:
      - args:
        - /nginx-ingress-controller
        - --default-backend-service=$(POD_NAMESPACE)/default-http-backend
        - --default-ssl-certificate=$(POD_NAMESPACE)/tls-certificate
        - --ingress-class=nginx
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        image: quay.io/kubernetes-ingress-controller/nginx-ingress-controller:0.23.0
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /healthz
            port: 10254
            scheme: HTTP
          initialDelaySeconds: 10
          timeoutSeconds: 5
        name: nginx-ingress-controller
        ports:
        - containerPort: 80
          name: http
          protocol: TCP
        - containerPort: 443
          name: https
          protocol: TCP
        volumeMounts:
        - mountPath: /etc/nginx-ssl/dhparam
          name: tls-dhparam-vol
      terminationGracePeriodSeconds: 60
      volumes:
      - name: tls-dhparam-vol
        secret:
          secretName: tls-dhparam
