apiVersion: v1
data:
  POSTGRES_DB: hydra
  POSTGRES_PASSWORD: secret
  POSTGRES_USER: hydra
kind: ConfigMap
metadata:
  annotations:
    appGroup: hydra
  labels:
    app: postgres
  name: postgres-config
  namespace: hydra
---
apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    appGroup: hydra
  labels:
    app: postgres
    type: local
  name: postgres-pv-volume
  namespace: hydra
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 5Gi
  hostPath:
    path: <need modified>
  storageClassName: postgresdb
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    appGroup: hydra
  labels:
    app: postgres
  name: postgres-pv-claim
  namespace: hydra
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: postgresdb
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    appGroup: hydra
  name: postgres
  namespace: hydra
spec:
  ports:
  - name: postgres
    nodePort: 30432
    port: 5432
    targetPort: 5432
  selector:
    app: postgres
  type: NodePort
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    appGroup: hydra
  name: postgres
  namespace: hydra
spec:
  replicas: 1
  template:
    metadata:
      annotations:
        appGroup: hydra
      labels:
        app: postgres
    spec:
      containers:
      - envFrom:
        - configMapRef:
            name: postgres-config
        image: postgres:11.2
        imagePullPolicy: IfNotPresent
        name: postgres
        ports:
        - containerPort: 5432
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: postgredb
      volumes:
      - name: postgredb
        persistentVolumeClaim:
          claimName: postgres-pv-claim
