kind: Service
apiVersion: v1
metadata:
  name: postgres
spec:
  type: NodePort
  selector:
    app: postgres
  ports:
  - name: postgres
    port: 5432
    targetPort: 5432
    # The range of valid ports is 30000-32767
    nodePort: 30432