kind: PersistentVolume
apiVersion: v1
metadata:
  name: mysql-pv-volume
  labels:
    type: local
    app: mysql
spec:
  storageClassName: mysqldb
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    # TODO modified
    path: "<need modified>"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mysql-pv-claim
  labels:
    app: mysql
spec:
  storageClassName: mysqldb
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi