apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    appGroup: hydra
  labels:
    app: mysql
    type: local
  name: mysql-pv-volume
  namespace: hydra
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 5Gi
  hostPath:
    path: <need modified>
  storageClassName: mysqldb
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    appGroup: hydra
  labels:
    app: mysql
  name: mysql-pv-claim
  namespace: hydra
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: mysqldb
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    appGroup: hydra
  name: mysql
  namespace: hydra
spec:
  ports:
  - name: mysql
    nodePort: 30306
    port: 3306
    targetPort: 3306
  selector:
    app: mysql
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    appGroup: hydra
  name: mysql
  namespace: hydra
spec:
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      annotations:
        appGroup: hydra
      labels:
        app: mysql
    spec:
      containers:
      - env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              key: password
              name: mysql-secret
        image: mysql:5.6
        name: mysql
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - mountPath: /var/lib/mysql
          name: mysql-persistent-storage
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pv-claim
