apiVersion: v1
kind: Secret
metadata:
  name: hydra-secret
type: Opaque
data:
  # TODO change secret
  system.secret: cEhuVDFjRkVjeWw5QXZXNDlVWGdRSjh3SmtIS1Z3TDNUZ3Yza002RTFUM2Z0M01zNG53c0M4ckU3ZVVsRnN3MGxLUnJ6VGFkeGk1RDZPb2tIUGhycjdFNzlTSFRRaUMwM1R5bw==